#!/bin/sh

case "${1}" in
    start)
	hue2mqtt -c /boot/hue2mqtt.json &
	;;
    stop)
	kill -9 $(cat /var/run/hue2mqtt.pid)
	;;
    restart)
	kill -9 $(cat /var/run/hue2mqtt.pid)
	hue2mqtt -c /boot/hue2mqtt.json &
	;;
    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
